tencentcloud_captcha.settings:
  type: config_object
  label: 'TencentCloud Captcha settings'
  mapping:
    secret_id:
      type: string
      label: 'Secret Id'
    secret_key:
      type: string
      label: 'Secret key'
    app_id:
      type: string
      label: 'App Id'
    app_secret_key:
      type: string
      label: 'App Secret Key'
